#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DAYLY.Droid.Resource", IsApplication=true)]

namespace DAYLY.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020002
			public const int add = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int arrow_icon = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int automation_icon = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int breaks_icon = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int calendar = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int circle_blue = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int circle_darkblue = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int circle_darkgreen = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int circle_green = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int circle_orange = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int circle_red = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int circle_yellow = 2130837517;
			
			// aapt resource value: 0x7F020000
			public const int Create_logo = 2130837504;
			
			// aapt resource value: 0x7F02000E
			public const int daily_active = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int daily_inactive = 2130837519;
			
			// aapt resource value: 0x7F020001
			public const int DAYLY = 2130837505;
			
			// aapt resource value: 0x7F020010
			public const int edit_icon = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int hike_calendar = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int home = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int icn_arrow = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int icn_month_view_active = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int icn_week_view_inactive = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int location_pin = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int logo_best = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int logo_title = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int monthly_active = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int monthly_inactive = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int path = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int profile = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int profile_background_image = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int profile_edit_icon = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int profile_icon = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int profile_pic = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int reminders_icon = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int settings = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int settings_icon = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int sync_and_data_icon = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int tab_about = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int tab_feed = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int tick_icon = 2130837543;
			
			// aapt resource value: 0x7F020028
			public const int transparent = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int user_placeholder = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public const int weekly_active = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int weekly_inactive = 2130837547;
			
			// aapt resource value: 0x7F02002C
			public const int weight_calendar = 2130837548;
			
			// aapt resource value: 0x7F02002D
			public const int xamarin_logo = 2130837549;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int sliding_tabs = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int toolbar = 2130903041;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Tabbar = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Toolbar = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int icon = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int icon_round = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int launcher_foreground = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int logo_best = 2131034115;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int MainTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
